# -*- coding: utf-8 -*-
"""BMD_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ka9jQOX-0dqEGUgvsyFPi0vsdkUHG1xF
"""

target='BMD_Value'
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv('bmd_dataset.csv')

df.head()

df.info()

for i in df.columns:
  print(df[i].min(),df[i].max())

df.describe()

df = df.iloc[:10000,:]

df.isna().sum() / len(df) * 100

df.duplicated().sum()

for col in df.columns:
  if df[col].dtype != "object":
    sns.kdeplot(df[col])
    plt.show()
    sns.boxplot(df[col])
    plt.show()

for col in df.columns:
  print(df[col].value_counts())
  print(df[col].nunique())
  print("--------------------------------------")

y=df['BMD_Value']
X=df.drop(columns='BMD_Value')

X.shape

y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 8)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

#Preprocessing
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

# Define categorical and numerical columns
categorical_cols = ['Gender', 'Smoking_Status', 'Alcohol_Consumption']
numerical_cols = [col for col in X.columns if col not in categorical_cols]

# Preprocessing pipelines
categorical_transformer = OneHotEncoder(drop='first', handle_unknown='ignore')
numerical_transformer = StandardScaler()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

# Fit the preprocessor on training data and transform both train and test
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, VotingRegressor, StackingRegressor, AdaBoostRegressor, GradientBoostingRegressor
import xgboost as xgb

# Initialize models
knn = KNeighborsRegressor()
decision_tree = DecisionTreeRegressor(random_state=42)
linear_reg = LinearRegression()
random_forest = RandomForestRegressor(n_estimators=100, random_state=42)
ada_boost = AdaBoostRegressor(random_state=42)
gradient_boost = GradientBoostingRegressor(random_state=42)
xtreme_gb = xgb.XGBRegressor(objective ='reg:squarederror', random_state=42)

# Voting Regressor
voting = VotingRegressor(estimators=[('knn', knn), ('dt', decision_tree), ('lr', linear_reg)])

# Stacking Regressor
estimators = [('rf', random_forest), ('ada', ada_boost), ('gb', gradient_boost)]
stacking = StackingRegressor(estimators=estimators, final_estimator=linear_reg)

# Fit models
models = {'KNN': knn, 'Decision Tree': decision_tree, 'Linear Regression': linear_reg, 'Random Forest': random_forest, 'AdaBoost': ada_boost, 'Gradient Boosting': gradient_boost, 'Xtreme GB': xtreme_gb, 'Voting': voting, 'Stacking': stacking}

for name, model in models.items():
    model.fit(X_train_processed, y_train)

predictions = {}
for name, model in models.items():
    predictions[name] = model.predict(X_test_processed)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

results = {}
for name, y_pred in predictions.items():
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse) # Fixed: Calculate RMSE by taking the square root of MSE
    r2 = r2_score(y_test, y_pred)
    results[name] = {'MSE': mse, 'RMSE': rmse, 'R2': r2}

# Display results
for name, metrics in results.items():
    print(f"{name} - R2: {metrics['R2']:.4f}, RMSE: {metrics['RMSE']:.4f}")

# Define parameter grids for models
param_grids = {
    'gradient_boost': {
        'n_estimators': [50, 100, 200],
        'learning_rate': [0.01, 0.1, 0.2],
        'max_depth': [3, 5, 10],
    }
}
# Initialize models
models = {
    'gradient_boost': GradientBoostingRegressor(random_state=42),
    'linear_regression': LinearRegression()
}

from sklearn.model_selection import GridSearchCV
best_estimators = {}

# Perform GridSearchCV for each model except Linear Regression
for name, model in models.items():
    if name == 'linear_regression':
        # Linear Regression has no hyperparameters to tune
        model.fit(X_train_processed, y_train)
        best_estimators[name] = model
        print(f"Fitted Linear Regression without tuning")
        continue

    print(f"Tuning {name}...")
    grid_search = GridSearchCV(model, param_grids[name], cv=5, scoring='r2', n_jobs=-1)
    grid_search.fit(X_train_processed, y_train)
    best_estimators[name] = grid_search.best_estimator_
    print(f"Best params for {name}: {grid_search.best_params_}")

# Pick the best model based on R2 score on validation (here using test set for demonstration)
from sklearn.metrics import r2_score

best_model_name = None
best_r2 = float('-inf')

for name, model in best_estimators.items():
    y_pred = model.predict(X_test_processed)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} - R2: {r2:.4f}")
    if r2 > best_r2:
        best_r2 = r2
        best_model_name = name

print(f"Best model: {best_model_name} with R2: {best_r2:.4f}")

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

results = {}
for name, y_pred in predictions.items():
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)
    results[name] = {'MSE': mse, 'RMSE': rmse, 'R2': r2}

# Display results
for name, metrics in results.items():
    print(f"{name} - R2: {metrics['R2']:.4f}, RMSE: {metrics['RMSE']:.4f}")

#Step 6: Verify Performance
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Generate predictions for the best models
predictions_best_models = {}
for name, model in best_estimators.items():
    predictions_best_models[name] = model.predict(X_test_processed)

# Calculate metrics for the best models
results_best_models = {}
for name, y_pred in predictions_best_models.items():
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)
    results_best_models[name] = {'MSE': mse, 'RMSE': rmse, 'R2': r2}

# Display results
print("\n--- Performance of Best Models ---")
for name, metrics in results_best_models.items():
    print(f"{name} - R2: {metrics['R2']:.4f}, RMSE: {metrics['RMSE']:.4f}")

# Plot R2 scores
model_names = list(results_best_models.keys())
r2_scores = [results_best_models[name]['R2'] for name in model_names]
plt.figure(figsize=(12,6))
sns.barplot(x=model_names, y=r2_scores)
plt.title('Best Models R2 Scores Comparison')
plt.ylabel('R2 Score')
plt.xlabel('Model')
plt.show()

import joblib
joblib.dump(linear_reg, 'BMD_RG_value.pkl')

