# -*- coding: utf-8 -*-
"""BMD_FINALL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbL56818gtbsydhBdEf5IEB47KwuNv25

# Bone Mineral Density (BMD) Prediction using Machine Learning

## 1. Problem Statement
- Bone Mineral Density (BMD) is a key indicator used to diagnose osteoporosis and other bone-related diseases. Early prediction of BMD values can help doctors identify patients who are at risk.

- The goal of this project is to build a machine learning model that predicts BMD values using patient demographic and lifestyle attributes.

## 2. Project Objective

### The main objectives of this project were:

- Build a complete end-to-end machine learning pipeline

- Train multiple regression models

- Compare their performances

- Improve models using hyperparameter tuning

- Select the best performing model

- Deploy the model as a web application
"""

# ============================================
# 1. IMPORT LIBRARIES
# ============================================
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

# ============================================
# 2. LOAD DATA
# ============================================
df = pd.read_csv("bmd_dataset.csv")

df.info()  #Information about Data

"""## 3. Dataset Description

- The dataset contains information about patients and their lifestyle habits.

### Example features include:

- Age

- Gender

- Smoking status

- Alcohol consumption

- BMI

- Target variable: BMD_Value

- This value represents the bone mineral density level of a patient.
"""

df.head()  #Top 5 rows

"""## 4. Data Cleaning"""

# Checked for missing values
print("\nMissing values:\n", df.isnull().sum())

#checking for duplicates
df.duplicated().sum()

for i in df.columns:
    print(i,df[i].nunique()) #for unique value counts

# ============================================
# 4. FEATURE / TARGET SPLIT
# ============================================
X = df.drop("BMD_Value", axis=1)
y = df["BMD_Value"]

"""# 5. Data Splitting

- The dataset was divided into:

- Training Data (80%)

- Testing Data (20%)

- Training data is used to train the models, while testing data evaluates how well the model generalizes to unseen data.
"""

# ============================================
# 5. TRAIN TEST SPLIT
# ============================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""## 6. Data Preprocessing

- Since the dataset contains both numerical and categorical features, preprocessing was required.

#### Numerical Features

- Standardized using:

-StandardScaler

#### Categorical Features

- Encoded using:

- OneHotEncoder

#### Pipeline

- A ColumnTransformer pipeline was used to apply preprocessing steps automatically.

- This ensures the same transformations are applied during training and prediction.
"""

# ============================================
# 6. PREPROCESSING (ROBUST SCALER)
# ============================================
numeric_features = [
    "Age",
    "BMI",
    "Physical_Activity_Min",
    "Calcium_Intake_mg"
]

categorical_features = [
    "Gender",
    "Smoking_Status",
    "Alcohol_Consumption"
]

preprocessor = ColumnTransformer([
    ("num", RobustScaler(), numeric_features),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
])

"""## 7. Model Building

- Multiple regression algorithms were trained to compare their performance.

#### The models used were:

- KNN Regressor

- Decision Tree Regressor

- Linear Regression

- Random Forest Regressor

- AdaBoost Regressor

- Gradient Boosting Regressor

- XGBoost Regressor

- Using multiple algorithms allows us to identify which model performs best for this dataset.
"""

# ============================================
# 7. MODEL DEFINITIONS
# ============================================
models = {
    "Linear": LinearRegression(),
    "KNN": KNeighborsRegressor(),
    "DecisionTree": DecisionTreeRegressor(),
    "RandomForest": RandomForestRegressor(),
    "AdaBoost": AdaBoostRegressor(),
    "GradientBoost": GradientBoostingRegressor(),
    "XGBoost": XGBRegressor(objective="reg:squarederror")
}

"""## 8. Model Evaluation

#### Models were evaluated using the following metrics:

- R² Score

     Measures how well the model explains variance in the target variable.

- RMSE (Root Mean Squared Error)

     Measures prediction error magnitude.


- The model with higher R² score and lower RMSE is considered better.
"""

# ============================================
# 8. BASELINE TRAINING + LEADERBOARD
# ============================================
leaderboard = []

for name, model in models.items():

    pipe = Pipeline([
        ("preprocess", preprocessor),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)
    pred = pipe.predict(X_test)

    r2 = r2_score(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))

    leaderboard.append([name, r2, rmse])

results_df = pd.DataFrame(
    leaderboard,
    columns=["Model", "R2 Score", "RMSE"]
)

results_df = results_df.sort_values(by="R2 Score", ascending=False)

print("\nMODEL PERFORMANCE LEADERBOARD\n")
print(results_df)

best_model_name = results_df.iloc[0]["Model"]
print("\nBest baseline model:", best_model_name)

"""## 9. Hyperparameter Tuning

#### To improve model performance, GridSearchCV was used to tune parameters for models such as:

- Random Forest

- Gradient Boosting

- AdaBoost

- XGBoost

- KNN

- Hyperparameter tuning helps find the optimal configuration for each model.
"""

tuned_leaderboard_results = []
param_grids = {
    "Linear": {}, # Added placeholder for Linear Regression as it's a model in 'models'
    "KNN": {"model__n_neighbors": [3,5,7,9]},
    "DecisionTree": {"model__max_depth": [3,5,7,None]},
    "RandomForest": {
        "model__n_estimators": [100,200],
        "model__max_depth": [5,10,None]
    },
    "AdaBoost": {
        "model__n_estimators": [50,100],
        "model__learning_rate": [0.05,0.1]
    },
    "GradientBoost": {
        "model__n_estimators": [100,200],
        "model__learning_rate": [0.05,0.1]
    },
    "XGBoost": {
        "model__n_estimators": [100,200],
        "model__max_depth": [3,5],
        "model__learning_rate": [0.05,0.1]
    }
}

models_tuned_estimators = {} # Dictionary to store the best estimator for each model

# Corrected iteration: Loop through the actual model objects
for name, model_instance in models.items():
    print(f"\nTuning {name} model...")
    pipe = Pipeline([
        ("preprocess", preprocessor),
        ("model", model_instance) # model_instance is now the actual sklearn estimator
    ])

    # Logic to decide if tuning is needed and if RandomForest should be skipped
    if name in param_grids and param_grids[name] and name != 'RandomForest':
        print(f"Applying GridSearchCV for {name}...")
        grid_search = GridSearchCV(
            pipe,
            param_grids[name], # param_grids[name] contains the parameters for this specific model
            cv=5,
            scoring="r2",
            n_jobs=-1  # Use all available cores
        )
        grid_search.fit(X_train, y_train)
        best_estimator = grid_search.best_estimator_
        best_params = grid_search.best_params_
        print(f"Best parameters for {name}: {best_params}")
    else:
        # For models like Linear (which has an empty param_grid) or RandomForest (explicitly skipped)
        if name == 'RandomForest':
            print(f"Skipping hyperparameter tuning for RandomForest as requested. Using baseline model.")
        elif name in param_grids and not param_grids[name]: # For models with empty param_grid
            print(f"No specific tuning parameters defined for {name}. Using baseline model.")
        else: # Fallback for models not in param_grids or other cases (shouldn't happen with current setup)
            print(f"No tuning parameters found or tuning skipped for {name}. Using baseline model.")
        best_estimator = pipe
        best_estimator.fit(X_train, y_train) # Fit the baseline pipeline

    models_tuned_estimators[name] = best_estimator # Store the best estimator for this model

    pred = best_estimator.predict(X_test)
    r2 = r2_score(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))

    tuned_leaderboard_results.append([name, r2, rmse])

# Create a DataFrame for tuned results
tuned_results_df = pd.DataFrame(
    tuned_leaderboard_results,
    columns=["Model", "Tuned R2 Score", "Tuned RMSE"]
)

tuned_results_df = tuned_results_df.sort_values(by="Tuned R2 Score", ascending=False)

print("\n=========================================")
print("TUNED MODEL PERFORMANCE LEADERBOARD")
print("=========================================")
print(tuned_results_df)

# Select the overall best model based on the tuned results
best_tuned_model_name = tuned_results_df.iloc[0]["Model"]
final_model = models_tuned_estimators[best_tuned_model_name] # Assign the overall best estimator

print(f"\nOverall best tuned model selected: {best_tuned_model_name}")

# for Time saving use RandomizedSearchCV for RandomForest
from sklearn.model_selection import RandomizedSearchCV

# Define a smaller parameter grid
rf_param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [5, None],
    "model__min_samples_split": [2, 5],
    "model__min_samples_leaf": [1, 2]
}

# RandomForest model
rf_model = RandomForestRegressor(random_state=42)

# Pipeline
rf_pipeline = Pipeline([
    ("preprocess", preprocessor),   # your preprocessing steps
    ("model", rf_model)
])

# RandomizedSearchCV (fast alternative to GridSearchCV)
rf_random = RandomizedSearchCV(
    rf_pipeline,
    rf_param_grid,
    n_iter=5,        # only try 5 random combinations
    cv=3,            # fewer folds for speed
    scoring="r2",
    n_jobs=-1,
    random_state=42
)

# Fit
rf_random.fit(X_train, y_train)

# Best model
final_rf_model = rf_random.best_estimator_

# Predictions
rf_pred = final_rf_model.predict(X_test)

# Performance
print("\nFAST RANDOM FOREST PERFORMANCE")
print("Best Params:", rf_random.best_params_)
print("R2:", r2_score(y_test, rf_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, rf_pred)))

"""## 10. Best Model Selection

- After comparing all models and their tuned versions, the best performing model was selected based on evaluation metrics.

- The selected model was then used for deployment.
"""

# ============================================
# 10. SAVE BEST MODEL
# ============================================
with open("BMD_RG.pkl", "wb") as f:
    pickle.dump(final_model, f)

print("\nBest tuned model saved as BMD_RG.pkl")

"""# Key Insights from the BMD Prediction ML Project
##1️⃣ Age has a strong impact on Bone Mineral Density

- From exploratory analysis, age showed a strong relationship with BMD values.

### Insight:

- As age increases, BMD tends to decrease.

- This aligns with medical knowledge that bone density decreases with aging, especially after middle age.

- This indicates that age is one of the most important predictive features.

##2️⃣ Lifestyle factors influence bone health

### Variables such as:

- Smoking

- Alcohol consumption

- Physical habits

-  show influence on BMD values.

### Insight:

- Unhealthy lifestyle habits are associated with lower BMD levels.

- This highlights the role of preventive healthcare and lifestyle management.
"""

